In [10]:
import pandas as pd
import seaborn as sa
import matplotlib as mb
import numpy as np

**Lendo arquivo**

In [13]:
df = pd.read_csv('qualidade_ar_brasil.csv')

**INSPECIONANDO ARQUIVO**

In [3]:
df

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
0,2025-01-01,Brasília,DF,33.7,60.9,44.6,31.8,25.5,57.8,61.7,Moderado
1,2025-01-01,Curitiba,PR,25.7,22.1,29.4,40.0,17.1,77.4,43.4,Moderado
2,2025-01-01,Salvador,BA,18.8,27.6,29.2,60.2,29.3,78.0,47.5,Moderado
3,2025-01-02,Curitiba,PR,12.4,41.1,20.0,32.6,20.3,85.7,35.8,Bom
4,2025-01-03,Belo Horizonte,MG,32.0,57.3,36.4,23.5,26.3,74.6,54.1,Moderado
...,...,...,...,...,...,...,...,...,...,...,...
795,2025-12-30,São Paulo,SP,21.6,33.8,56.4,57.4,19.6,80.1,60.1,Moderado
796,2025-12-31,Belo Horizonte,MG,31.4,59.5,41.7,21.5,22.7,64.4,55.8,Moderado
797,2025-12-31,Fortaleza,CE,28.9,46.4,30.5,38.4,30.5,72.7,51.8,Moderado
798,2025-12-31,Manaus,AM,30.2,46.6,16.4,19.0,31.5,92.6,41.2,Moderado
799,2025-12-31,Porto Alegre,RS,17.7,46.3,24.5,34.1,21.8,80.8,42.3,Moderado

In [4]:
df.head()

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
0,2025-01-01,Brasília,DF,33.7,60.9,44.6,31.8,25.5,57.8,61.7,Moderado
1,2025-01-01,Curitiba,PR,25.7,22.1,29.4,40.0,17.1,77.4,43.4,Moderado
2,2025-01-01,Salvador,BA,18.8,27.6,29.2,60.2,29.3,78.0,47.5,Moderado
3,2025-01-02,Curitiba,PR,12.4,41.1,20.0,32.6,20.3,85.7,35.8,Bom
4,2025-01-03,Belo Horizonte,MG,32.0,57.3,36.4,23.5,26.3,74.6,54.1,Moderado

In [5]:
df.tail()

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
795,2025-12-30,São Paulo,SP,21.6,33.8,56.4,57.4,19.6,80.1,60.1,Moderado
796,2025-12-31,Belo Horizonte,MG,31.4,59.5,41.7,21.5,22.7,64.4,55.8,Moderado
797,2025-12-31,Fortaleza,CE,28.9,46.4,30.5,38.4,30.5,72.7,51.8,Moderado
798,2025-12-31,Manaus,AM,30.2,46.6,16.4,19.0,31.5,92.6,41.2,Moderado
799,2025-12-31,Porto Alegre,RS,17.7,46.3,24.5,34.1,21.8,80.8,42.3,Moderado

In [6]:
df.shape

(800, 11)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data                 800 non-null    object
 1   cidade               800 non-null    object
 2   estado               800 non-null    object
 3   pm25                 800 non-null    float64
 4   pm10                 800 non-null    float64
 5   no2                  800 non-null    float64
 6   o3                   800 non-null    float64
 7   temperatura          800 non-null    float64
 8   umidade              800 non-null    float64
 9   indice_qualidade_ar  800 non-null    float64
 10  nivel_alerta         800 non-null    object
dtypes: float64(7), object(4)
memory usage: 68.9+ KB

In [9]:
df.describe()

,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,26.597625,46.84950,27.537125,32.405125,25.640500,74.918750,47.758375
std,8.983311,13.63357,9.157577,9.247010,4.608675,9.492972,8.747129
min,6.000000,12.20000,5.000000,8.000000,14.500000,47.300000,28.600000
25%,20.400000,37.10000,21.700000,25.400000,22.300000,69.275000,41.600000
50%,25.900000,46.30000,26.800000,32.500000,25.850000,76.250000,46.900000
75%,32.000000,55.10000,32.900000,38.400000,29.100000,81.425000,53.500000
max,60.100000,91.60000,61.700000,68.100000,36.100000,96.000000,86.300000

In [11]:
df.isnull().sum()

data                   0
cidade                 0
estado                 0
pm25                   0
pm10                   0
no2                    0
o3                     0
temperatura            0
umidade                0
indice_qualidade_ar    0
nivel_alerta           0
dtype: int64

**CIDADES LISTADAS NA TABELA**

In [15]:
df['cidade'].unique()

array(['Brasília', 'Curitiba', 'Salvador', 'Belo Horizonte', 'Recife',
       'Fortaleza', 'Rio de Janeiro', 'Porto Alegre', 'Manaus',
       'São Paulo'], dtype=object)

In [16]:
df.groupby('cidade')[['pm25', 'pm10', 'no2', 'o3']].mean()

                     pm25       pm10        no2         o3
cidade
Belo Horizonte  27.874026  48.409091  27.992208  30.141558
Brasília        31.351724  59.428736  29.926437  33.167816
Curitiba        25.339785  43.408602  26.151613  28.435484
Fortaleza       23.186250  44.662500  24.232500  34.176250
Manaus          26.271084  46.898795  22.566265  30.354217
Porto Alegre    26.798592  47.760563  27.959155  27.991549
Recife          23.416471  41.165882  24.320000  32.205882
Rio de Janeiro  27.825301  43.106024  30.925301  38.836145
Salvador        21.503896  39.102597  24.568831  34.274026
São Paulo       33.653125  56.256250  39.314062  34.878125

**PERGUNTAS - PARTE-2**



*   1- 800
*   2- 10 cidades
*   3- 4 Colunas
*   4- Não

**PERGUNTAS - PARTE-3**



*   1- São Paulo
*   2- São Paulo
*   3- São Paulo

In [19]:
df.groupby('cidade')['indice_qualidade_ar'].mean().sort_values(ascending=False)

cidade
São Paulo         59.345312
Brasília          54.955172
Rio de Janeiro    50.639759
Belo Horizonte    48.344156
Porto Alegre      46.898592
Manaus            45.092771
Fortaleza         44.646250
Curitiba          44.359140
Recife            43.198824
Salvador          42.342857
Name: indice_qualidade_ar, dtype: float64

**PERGUNTAS - PARTE-4**
*   1- São Paulo
*   2- Salvador

In [24]:
df_alerta = df[df['nivel_alerta'].isin(['Ruim', 'Muito Ruim'])]
df_alerta

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
235,2025-04-20,São Paulo,SP,33.7,73.7,57.2,34.3,25.9,61.1,70.8,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,28.1,78.9,72.7,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,25.2,36.2,31.7,74.9,71.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,28.6,51.0,73.5,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim
379,2025-07-03,São Paulo,SP,51.7,78.9,48.3,26.8,21.6,68.0,76.1,Ruim
402,2025-07-12,São Paulo,SP,43.1,64.6,35.4,50.1,23.4,74.6,70.0,Ruim
408,2025-07-15,São Paulo,SP,38.3,72.1,35.3,53.2,23.9,66.8,70.5,Ruim
410,2025-07-15,São Paulo,SP,42.4,87.6,44.6,40.2,21.2,74.7,76.5,Ruim
411,2025-07-15,São Paulo,SP,35.8,91.6,41.6,36.7,22.4,79.9,71.8,Ruim
431,2025-07-27,São Paulo,SP,60.1,50.0,56.4,54.8,25.2,76.3,84.3,Ruim
488,2025-08-19,São Paulo,SP,55.2,78.8,55.0,45.3,20.3,80.3,86.3,Ruim
498,2025-08-22,Rio de Janeiro,RJ,44.5,58.9,41.7,45.8,26.1,81.9,70.2,Ruim
548,2025-09-17,Brasília,DF,54.3,69.2,37.4,36.0,23.8,62.5,73.6,Ruim

**PERGUNTAS - PARTE-5**



*   1- 14
*   2- São Paulo

In [25]:
df.sort_values('indice_qualidade_ar', ascending=False).head(10)

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
488,2025-08-19,São Paulo,SP,55.2,78.8,55.0,45.3,20.3,80.3,86.3,Ruim
431,2025-07-27,São Paulo,SP,60.1,50.0,56.4,54.8,25.2,76.3,84.3,Ruim
410,2025-07-15,São Paulo,SP,42.4,87.6,44.6,40.2,21.2,74.7,76.5,Ruim
379,2025-07-03,São Paulo,SP,51.7,78.9,48.3,26.8,21.6,68.0,76.1,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim
548,2025-09-17,Brasília,DF,54.3,69.2,37.4,36.0,23.8,62.5,73.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,28.6,51.0,73.5,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,28.1,78.9,72.7,Ruim
411,2025-07-15,São Paulo,SP,35.8,91.6,41.6,36.7,22.4,79.9,71.8,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,25.2,36.2,31.7,74.9,71.6,Ruim

**PERGUNTAS - PARTE-6**

* 1. Qual foi o pior dia registrado? - 19/08/2025
* 2. Em qual cidade ocorreu? São Paulo
* 3. Quais poluentes estavam mais altos nesse dia? PM10

In [27]:
df['data'] = pd.to_datetime(df['data'])

In [28]:
df['mes'] = df['data'].dt.month

In [29]:
df.groupby('mes')['indice_qualidade_ar'].mean()

mes
1     44.852308
2     42.985714
3     46.675949
4     47.559259
5     47.107813
6     52.881034
7     51.293443
8     49.640000
9     49.923333
10    47.865385
11    46.861429
12    45.829333
Name: indice_qualidade_ar, dtype: float64

**PERGUNTAS - PARTE-7**

* 1. Em quais meses a qualidade do ar tende a ser pior? Mês 6
* 2. Existe algum padrão sazonal? Sim

In [30]:
df[['temperatura', 'pm25', 'pm10', 'no2', 'o3']].corr()

             temperatura      pm25      pm10       no2        o3
temperatura     1.000000 -0.114987 -0.112821 -0.168689  0.160547
pm25           -0.114987  1.000000  0.253494  0.124651  0.022676
pm10           -0.112821  0.253494  1.000000  0.151211 -0.002501
no2            -0.168689  0.124651  0.151211  1.000000  0.048104
o3              0.160547  0.022676 -0.002501  0.048104  1.000000

**PERGUNTAS - PARTE-8**

* 1. Existe correlação entre temperatura e poluição? Sim
* 2. Quais poluentes parecem mais relacionados entre si? PM25 e PM10

**PERGUNTAS - DESAFIO FINAL**

* 1. Qual cidade apresenta pior qualidade média do ar? São Paulo
* 2. Quais poluentes são mais críticos? PM10 e o NO2
* 3. Existem meses mais problemáticos? Sim
* 4. Quais cidades deveriam receber maior atenção das autoridades ambientais? São Paulo, Brasília e Rio de Janeiro